(function(root){
'use strict';
const hex=bytes=>[...bytes].map(value=>value.toString(16).padStart(2,'0')).join('');
function parseCapture(buffer){
 const view=new DataView(buffer),bytes=new Uint8Array(buffer);if(view.byteLength<4)throw Error('capture is too short');
 const magic=view.getUint32(0,false);
 if(magic===0x0a0d0d0a)return parsePcapng(view,bytes);
 let little,nanos=false;if(magic===0xd4c3b2a1)little=true;else if(magic===0xa1b2c3d4)little=false;else if(magic===0x4d3cb2a1){little=true;nanos=true}else if(magic===0xa1b23c4d)nanos=true;else throw Error('unsupported PCAP magic');
 if(view.byteLength<24)throw Error('truncated PCAP header');let pos=24,frame=1,out=[];
 while(pos<view.byteLength){if(pos+16>view.byteLength)throw Error(`truncated PCAP record #${frame}`);const sec=view.getUint32(pos,little),fraction=view.getUint32(pos+4,little),length=view.getUint32(pos+8,little);pos+=16;if(length>view.byteLength-pos)throw Error(`truncated PCAP packet #${frame}`);const packet=bytes.slice(pos,pos+length);out.push({frame,timestamp_us:sec*1e6+Math.floor(fraction/(nanos?1000:1)),length,wire_hex:hex(packet)});pos+=length;frame++}
 return out;
}
function parsePcapng(view,bytes){let pos=0,little=true,frame=1,out=[];while(pos<view.byteLength){if(pos+12>view.byteLength)throw Error('truncated PCAPNG block');const section=view.getUint32(pos,false)===0x0a0d0d0a;if(section){const bom=view.getUint32(pos+8,false);if(bom===0x4d3c2b1a)little=true;else if(bom===0x1a2b3c4d)little=false;else throw Error('invalid PCAPNG byte-order magic')}const type=section?0x0a0d0d0a:view.getUint32(pos,little),length=view.getUint32(pos+4,little);if(length<12||pos+length>view.byteLength||view.getUint32(pos+length-4,little)!==length)throw Error('invalid PCAPNG block length');if(type===0x00000006){if(length<32)throw Error('truncated enhanced packet block');const high=view.getUint32(pos+12,little),low=view.getUint32(pos+16,little),captured=view.getUint32(pos+20,little);if(captured>length-32)throw Error('invalid PCAPNG captured length');const packet=bytes.slice(pos+28,pos+28+captured);out.push({frame,timestamp_us:high*4294967296+low,length:captured,wire_hex:hex(packet)});frame++}pos+=length}return out}
function matchCapture(events,packets){const used=new Set;return events.map(event=>{if(!event.wire_hex)return{event,frame:null,match:'no-wire'};const target=event.wire_hex.toLowerCase();let index=packets.findIndex((packet,i)=>!used.has(i)&&packet.wire_hex.toLowerCase()===target);let match='exact';if(index<0){index=packets.findIndex((packet,i)=>!used.has(i)&&(packet.wire_hex.toLowerCase().includes(target)||target.includes(packet.wire_hex.toLowerCase())));match=index<0?'missing':'contained'}if(index>=0)used.add(index);return{event,frame:index>=0?packets[index].frame:null,match}})}
function decodeSchemas(wireHex,schemas){const clean=(wireHex||'').replace(/\s/g,'');if(!/^[0-9a-f]*$/i.test(clean)||clean.length%2)throw Error('wire data is not valid hex');const bytes=Uint8Array.from(clean.match(/../g)||[],value=>parseInt(value,16));return(schemas||[]).map(schema=>({name:schema.name,fields:Object.fromEntries((schema.fields||[]).map(field=>[field.name,decodeField(bytes,schema,field)]))}))}
function decodeField(bytes,schema,field){const start=(schema.offset||0)+(field.offset||0),part=bytes.slice(start,start+field.length);if(part.length!==field.length)return null;if(field.format==='hex')return hex(part);if(field.format==='ascii')return new TextDecoder().decode(part);if(field.format==='ipv4'&&part.length===4)return[...part].join('.');let value=0n;if(schema.endian==='little'){for(let i=part.length-1;i>=0;i--)value=(value<<8n)|BigInt(part[i])}else for(const byte of part)value=(value<<8n)|BigInt(byte);const width=BigInt(field.bits||field.length*8),shift=BigInt(field.bit_offset||0),mask=(1n<<width)-1n;value=(value>>shift)&mask;return value<=BigInt(Number.MAX_SAFE_INTEGER)?Number(value):value.toString()}
function snapshot(manifest,traces){const events=(traces||[]).flatMap(trace=>trace?.events||[]),failed=(traces||[]).some(trace=>trace?.status==='fail');return{id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,created_at:new Date().toISOString(),protocol:manifest.protocol.name,status:failed?'fail':'ok',duration_us:Math.max(0,...events.map(event=>event.timestamp_us||0)),event_count:events.length,failed_steps:[...new Set(events.filter(event=>!event.ok).map(event=>event.step))],events:events.slice(0,2000).map(event=>({step:event.step,action:event.action,ok:event.ok,detail:event.detail||'',timestamp_us:event.timestamp_us,wire_hex:(event.wire_hex||'').slice(0,8192)}))}}
function compareSnapshots(previous,current){if(!previous)return{classification:'baseline',new_failures:[],resolved:[],packet_changes:[],duration_delta_us:0,event_delta:0};const before=new Set(previous.failed_steps||[]),after=new Set(current.failed_steps||[]),newFailures=[...after].filter(item=>!before.has(item)),resolved=[...before].filter(item=>!after.has(item)),priorPackets=new Map((previous.events||[]).filter(event=>event.wire_hex).map(event=>[event.step,event.wire_hex])),currentPackets=new Map((current.events||[]).filter(event=>event.wire_hex).map(event=>[event.step,event.wire_hex])),packetChanges=[...new Set([...priorPackets.keys(),...currentPackets.keys()])].filter(step=>priorPackets.get(step)!==currentPackets.get(step)),duration=current.duration_us-previous.duration_us,eventDelta=current.event_count-previous.event_count,classification=newFailures.length||previous.status==='ok'&&current.status==='fail'||packetChanges.length?'regression':resolved.length||previous.status==='fail'&&current.status==='ok'?'improvement':duration>Math.max(1000,previous.duration_us*.1)?'slower':'unchanged';return{classification,new_failures:newFailures,resolved,packet_changes:packetChanges,duration_delta_us:duration,event_delta:eventDelta}}
root.tcpformAnalysis={parseCapture,matchCapture,decodeSchemas,snapshot,compareSnapshots};
})(typeof window==='undefined'?globalThis:window);
