(function(root){'use strict';
root.tcpformVirtualRender=function(host,rows,render,{rowHeight=42,height=320,overscan=8,summary=''}={}){host.className='virtual-collection';host.innerHTML=`${summary}<div class="virtual-viewport" style="height:${height}px;overflow:auto;position:relative"><div style="height:${rows.length*rowHeight}px;position:relative"><div class="virtual-window" style="position:absolute;left:0;right:0"></div></div></div>`;const viewport=host.querySelector('.virtual-viewport'),windowHost=host.querySelector('.virtual-window'),draw=()=>{const range=root.tcpformWorkbench.virtualWindow({scrollTop:viewport.scrollTop,rowHeight,viewportHeight:viewport.clientHeight,total:rows.length,overscan});windowHost.style.transform=`translateY(${range.offset}px)`;windowHost.innerHTML=rows.slice(range.start,range.end).map((row,index)=>render(row,range.start+index)).join('')};viewport.addEventListener('scroll',draw,{passive:true});draw()};
root.setupPlatformUi=function(){
  const saved=JSON.parse(localStorage.getItem('tcpform.ui.v1')||'{}'),params=new URLSearchParams(location.hash.slice(1));
  document.documentElement.dataset.theme=params.get('theme')||saved.theme||'dark';document.documentElement.lang=params.get('lang')||saved.lang||'ja';
  const ja={'View controls':'表示設定','DSL editor':'DSL エディタ','Protocol plan':'プロトコル計画','Role interaction flow':'ロール間フロー','Trace time axis':'トレース時間軸','Error / step inspector':'エラー・ステップ調査','Case comparison':'ケース比較','Cases / branches':'ケース・分岐','Capture alignment / DSL generation':'キャプチャ照合・DSL生成','Packet bit / header editor':'パケットビット・ヘッダ編集','Live execution':'ライブ実行','Execution history / regression':'実行履歴・回帰','Run statistics / coverage':'実行統計・カバレッジ','Protocol workbench':'プロトコル・ワークベンチ','Runtime trace':'ランタイムトレース'},headings=[...document.querySelectorAll('.panel h2')];headings.forEach(node=>node.dataset.en=node.textContent);const applyLanguage=()=>{headings.forEach(node=>node.textContent=document.documentElement.lang==='ja'?(ja[node.dataset.en]||node.dataset.en):node.dataset.en);document.getElementById('command-open')?.replaceChildren(document.createTextNode(document.documentElement.lang==='ja'?'⌘ コマンド':'⌘ Commands'));document.getElementById('theme-toggle')?.replaceChildren(document.createTextNode(document.documentElement.lang==='ja'?'テーマ':'Theme'))};
  const bar=document.createElement('nav');bar.className='platform-bar';bar.setAttribute('aria-label','Workspace views');bar.innerHTML='<button data-view="all" class="active">All</button><button data-view="flow">Flow</button><button data-view="inspect">Inspect</button><button data-view="workbench">Workbench</button><span class="spacer"></span><button id="command-open" title="Ctrl/Cmd+K">⌘ Commands</button><button id="theme-toggle">Theme</button><button id="language-toggle">日本語/EN</button>';document.querySelector('header').after(bar);
  const panels=[...document.querySelectorAll('.panel')],classify=panel=>{const title=panel.querySelector('h2')?.textContent||'';if(/plan|flow|trace time|Runtime trace/i.test(title))return'flow';if(/inspector|comparison|packet|capture|history|statistics/i.test(title))return'inspect';if(/workbench|editor|Live execution/i.test(title))return'workbench';return'all'},persist=()=>{saved.theme=document.documentElement.dataset.theme;saved.lang=document.documentElement.lang;localStorage.setItem('tcpform.ui.v1',JSON.stringify(saved));history.replaceState(null,'','#'+new URLSearchParams({theme:saved.theme,lang:saved.lang,view:saved.view||'all'}))};
  panels.forEach(panel=>panel.dataset.platformView=classify(panel));const activate=view=>{bar.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));panels.forEach(panel=>panel.dataset.platformHidden=String(view!=='all'&&panel.dataset.platformView!==view&&panel.dataset.platformView!=='all'));saved.view=view;persist()};bar.onclick=event=>{const button=event.target.closest('[data-view]');if(button)activate(button.dataset.view)};
  document.getElementById('theme-toggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';persist()};document.getElementById('language-toggle').onclick=()=>{document.documentElement.lang=document.documentElement.lang==='ja'?'en':'ja';applyLanguage();persist()};applyLanguage();
  const commands=[['Flow view',()=>activate('flow')],['Inspector view',()=>activate('inspect')],['Workbench view',()=>activate('workbench')],['Show all',()=>activate('all')],['Run source',()=>root.runSources()],['Play trace',()=>root.play()],['Toggle theme',()=>document.getElementById('theme-toggle').click()],['Open files',()=>document.getElementById('bundle-files').click()]],openPalette=()=>{document.querySelector('.command-palette')?.remove();const host=document.createElement('div');host.className='command-palette';host.setAttribute('role','dialog');host.innerHTML='<input aria-label="Find command" placeholder="Type a command…"><div></div>';document.body.append(host);const input=host.querySelector('input'),results=host.querySelector('div'),render=()=>results.innerHTML=commands.filter(([name])=>name.toLowerCase().includes(input.value.toLowerCase())).map(([name])=>`<button data-command="${name}">${name}</button>`).join('');input.oninput=render;results.onclick=event=>{const button=event.target.closest('[data-command]');if(!button)return;host.remove();commands.find(item=>item[0]===button.dataset.command)?.[1]()};input.onkeydown=event=>{if(event.key==='Escape')host.remove();if(event.key==='Enter')results.querySelector('button')?.click()};render();input.focus()};
  document.getElementById('command-open').onclick=openPalette;document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openPalette()}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();root.runSources()}if(event.key==='Escape')document.querySelector('.command-palette')?.remove()});window.addEventListener('error',event=>{const banner=document.createElement('div');banner.className='crash-banner';banner.setAttribute('role','alert');banner.textContent=`UI error: ${event.message} — workspace state was preserved`;document.body.append(banner);setTimeout(()=>banner.remove(),10000)});document.querySelectorAll('button:not([aria-label])').forEach(button=>button.setAttribute('aria-label',button.textContent.trim()||button.title));activate(params.get('view')||saved.view||'all');
};
})(window);
