//! Generate deterministic boofuzz harnesses and AFLNet seed corpora.

use crate::model::{Action, Protocol};
use serde::Serialize;

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct SeedMessage {
    pub index: usize,
    pub step: String,
    pub offset: usize,
    pub length: usize,
    pub hex: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct AflNetManifest {
    pub schema_version: &'static str,
    pub protocol: String,
    pub role: String,
    pub seed_file: &'static str,
    pub messages: Vec<SeedMessage>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AflNetExport {
    pub seed: Vec<u8>,
    pub manifest: AflNetManifest,
    pub dictionary: String,
}

pub fn boofuzz_script(
    protocol: &Protocol,
    role: &str,
    default_host: &str,
    default_port: u16,
) -> Result<String, String> {
    let messages = messages_for_role(protocol, role)?;
    let safe_names = messages
        .iter()
        .map(|(name, _)| python_identifier(name))
        .collect::<Vec<_>>();
    let mut definitions = String::new();
    for ((_, bytes), safe) in messages.iter().zip(&safe_names) {
        definitions.push_str(&format!(
            "    s_initialize({safe:?})\n    s_bytes(value=bytes.fromhex({:?}), fuzzable=True, name=\"payload\")\n",
            crate::bytes_to_hex(bytes)
        ));
    }
    let mut graph = format!("    session.connect(s_get({:?}))\n", safe_names[0]);
    for pair in safe_names.windows(2) {
        graph.push_str(&format!(
            "    session.connect(s_get({:?}), s_get({:?}))\n",
            pair[0], pair[1]
        ));
    }
    Ok(format!(
        "#!/usr/bin/env python3\n# Generated by tcpform. Run only against systems you are authorized to test.\nimport argparse\nfrom boofuzz import Session, Target, TCPSocketConnection, s_bytes, s_get, s_initialize\n\ndef main():\n    parser = argparse.ArgumentParser()\n    parser.add_argument(\"--host\", default={default_host:?})\n    parser.add_argument(\"--port\", default={default_port}, type=int)\n    args = parser.parse_args()\n    session = Session(target=Target(connection=TCPSocketConnection(args.host, args.port)))\n{definitions}{graph}    session.fuzz()\n\nif __name__ == \"__main__\":\n    main()\n"
    ))
}

pub fn aflnet_seed(protocol: &Protocol, role: &str) -> Result<AflNetExport, String> {
    let messages = messages_for_role(protocol, role)?;
    let mut seed = Vec::new();
    let mut manifest_messages = Vec::new();
    let mut dictionary = String::from("# Generated by tcpform from static DSL payloads.\n");
    for (index, (step, bytes)) in messages.into_iter().enumerate() {
        let offset = seed.len();
        seed.extend_from_slice(&bytes);
        manifest_messages.push(SeedMessage {
            index: index + 1,
            step: step.clone(),
            offset,
            length: bytes.len(),
            hex: crate::bytes_to_hex(&bytes),
        });
        dictionary.push_str(&format!(
            "{}=\"{}\"\n",
            python_identifier(&step),
            bytes
                .iter()
                .map(|byte| format!("\\x{byte:02x}"))
                .collect::<String>()
        ));
    }
    Ok(AflNetExport {
        seed,
        manifest: AflNetManifest {
            schema_version: "1.0",
            protocol: protocol.name.clone(),
            role: role.into(),
            seed_file: "seed_0001.raw",
            messages: manifest_messages,
        },
        dictionary,
    })
}

fn messages_for_role(protocol: &Protocol, role: &str) -> Result<Vec<(String, Vec<u8>)>, String> {
    if !protocol.steps.iter().any(|step| step.role == role) {
        return Err(format!("protocol `{}` has no role `{role}`", protocol.name));
    }
    let mut messages = Vec::new();
    for step in protocol
        .steps
        .iter()
        .filter(|step| step.role == role && matches!(step.action, Action::Send | Action::SendRaw))
    {
        let Some(segment) = &step.segment else {
            continue;
        };
        let bytes = if let Some(hex) = &segment.hex {
            if hex.contains("${") {
                return Err(format!(
                    "step `{}` contains interpolated hex; provide a static seed payload",
                    step.name
                ));
            }
            crate::parse_hex(hex).map_err(|error| format!("step `{}`: {error}", step.name))?
        } else if let Some(payload) = &segment.payload {
            if payload.contains("${") {
                return Err(format!(
                    "step `{}` contains an interpolated payload; provide a static seed payload",
                    step.name
                ));
            }
            payload.as_bytes().to_vec()
        } else {
            continue;
        };
        if !bytes.is_empty() {
            messages.push((step.name.clone(), bytes));
        }
    }
    if messages.is_empty() {
        Err(format!(
            "protocol `{}` has no static send payloads for role `{role}`",
            protocol.name
        ))
    } else {
        Ok(messages)
    }
}

fn python_identifier(value: &str) -> String {
    let mut output = value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    if output.is_empty() || output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "step_");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn protocol() -> Protocol {
        let source = r#"protocol "fuzzable" {
          step "hello" { role="client" action="send" to="server" segment { payload="HELLO\\r\\n" } }
          step "response" { role="server" action="send" to="client" segment { hex="0102" } }
          step "command" { role="client" action="send" to="server" segment { hex="aabbcc" } }
        }"#;
        crate::model::interpret(&crate::parse_file(source).unwrap())
            .unwrap()
            .remove(0)
    }

    #[test]
    fn generates_ordered_boofuzz_graph_and_aflnet_corpus() {
        let protocol = protocol();
        let script = boofuzz_script(&protocol, "client", "127.0.0.1", 9000).unwrap();
        assert!(script.contains("TCPSocketConnection(args.host, args.port)"));
        assert!(script.contains("session.connect(s_get(\"hello\"), s_get(\"command\"))"));
        assert!(script.contains("48454c4c4f5c725c6e"));

        let export = aflnet_seed(&protocol, "client").unwrap();
        assert_eq!(export.manifest.messages.len(), 2);
        assert_eq!(export.manifest.messages[1].offset, 9);
        assert_eq!(&export.seed[9..], &[0xaa, 0xbb, 0xcc]);
        assert!(export.dictionary.contains("command=\"\\xaa\\xbb\\xcc\""));
    }

    #[test]
    fn rejects_unknown_roles_and_interpolated_payloads() {
        assert!(aflnet_seed(&protocol(), "missing").is_err());
        let source = r#"protocol "dynamic" { step "send" { role="client" action="send" segment { payload="${value}" } } }"#;
        let protocol = crate::model::interpret(&crate::parse_file(source).unwrap())
            .unwrap()
            .remove(0);
        assert!(boofuzz_script(&protocol, "client", "localhost", 1).is_err());
    }
}
