//! Conservative conversion between tcpform conversations and packetdrill packet events.

use crate::model::{Action, Protocol, Segment};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PacketdrillImport {
    pub dsl: String,
    pub warnings: Vec<String>,
}

pub fn export(protocol: &Protocol, local_role: &str) -> Result<String, String> {
    if !protocol.steps.iter().any(|step| step.role == local_role) {
        return Err(format!(
            "protocol `{}` has no local role `{local_role}`",
            protocol.name
        ));
    }
    let mut output = format!(
        "// Generated by tcpform for packetdrill local role `{local_role}`.\n// Packet-only script: add socket syscalls when testing a local application API.\n"
    );
    let mut emitted = 0usize;
    for step in protocol.steps.iter().filter(|step| {
        matches!(step.action, Action::Send | Action::SendRaw) && step.segment.is_some()
    }) {
        let segment = step.segment.as_ref().unwrap();
        let direction = if step.role == local_role { '>' } else { '<' };
        let delay = segment.delay_ms as f64 / 1000.0;
        let timestamp = if emitted == 0 && delay == 0.0 {
            "0".into()
        } else {
            format!("+{delay:.6}")
        };
        let line = if is_udp(segment) {
            format!("{timestamp} {direction} udp ({})", payload_length(segment)?)
        } else {
            let length = payload_length(segment)?;
            let sequence = segment.seq.unwrap_or(0).max(0) as usize;
            let flags = packetdrill_flags(&segment.flags);
            let ack = segment
                .ack
                .filter(|ack| *ack >= 0)
                .map(|ack| format!(" ack {ack}"))
                .unwrap_or_default();
            let window = segment
                .window
                .filter(|window| *window >= 0)
                .map(|window| format!(" win {window}"))
                .unwrap_or_default();
            format!(
                "{timestamp} {direction} {flags} {sequence}:{}({length}){ack}{window}",
                sequence + length
            )
        };
        output.push_str(&format!("{line}  // {}\n", step.name));
        emitted += 1;
    }
    if emitted == 0 {
        Err(format!(
            "protocol `{}` has no packet-producing send steps",
            protocol.name
        ))
    } else {
        Ok(output)
    }
}

pub fn import(
    source: &str,
    protocol: &str,
    local_role: &str,
    peer_role: &str,
) -> Result<PacketdrillImport, String> {
    validate_identifier(protocol, "protocol")?;
    validate_identifier(local_role, "local role")?;
    validate_identifier(peer_role, "peer role")?;
    if local_role == peer_role {
        return Err("local and peer roles must differ".into());
    }
    let event = regex_lite::Regex::new(
        r"^\s*(\+?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)|\*)\s+([<>])\s+(.+?)\s*$",
    )
    .unwrap();
    let tcp = regex_lite::Regex::new(r"^([A-Za-z.\-]+)\s+([0-9]+):([0-9]+)\(([0-9]+)\)(?:\s+ack\s+([0-9]+))?(?:\s+win\s+([0-9]+))?").unwrap();
    let udp =
        regex_lite::Regex::new(r"(?i)^udp(?:\s+[0-9]+\s*>\s*[0-9]+)?\s*\(([0-9]+)\)").unwrap();
    let mut packets = Vec::<ImportedPacket>::new();
    let mut warnings = Vec::new();
    let mut absolute = 0.0f64;
    for (line_index, raw) in source.lines().enumerate() {
        let line_number = line_index + 1;
        let line = raw.split("//").next().unwrap_or("").trim();
        if line.is_empty() || line.starts_with("--") {
            continue;
        }
        let Some(captures) = event.captures(line) else {
            warnings.push(format!(
                "line {line_number}: skipped option, command, or system call"
            ));
            continue;
        };
        let time = captures.get(1).unwrap().as_str();
        let delay_ms = if time == "*" {
            0
        } else if let Some(relative) = time.strip_prefix('+') {
            (parse_seconds(relative, line_number)? * 1000.0).round() as u64
        } else {
            let next = parse_seconds(time, line_number)?;
            let delta = (next - absolute).max(0.0);
            absolute = next;
            (delta * 1000.0).round() as u64
        };
        let direction = captures.get(2).unwrap().as_str();
        let packet = captures.get(3).unwrap().as_str();
        let (flags, sequence, acknowledgement, window, payload_len, transport) =
            if let Some(fields) = tcp.captures(packet) {
                let flags = tcpform_flags(fields.get(1).unwrap().as_str());
                let sequence = fields.get(2).unwrap().as_str().parse().unwrap();
                let stated_end: usize = fields.get(3).unwrap().as_str().parse().unwrap();
                let payload_len: usize = fields.get(4).unwrap().as_str().parse().unwrap();
                if stated_end != sequence + payload_len {
                    warnings.push(format!(
                        "line {line_number}: sequence range does not equal payload length"
                    ));
                }
                (
                    flags,
                    Some(sequence),
                    fields.get(5).map(|value| value.as_str().parse().unwrap()),
                    fields.get(6).map(|value| value.as_str().parse().unwrap()),
                    payload_len,
                    "tcp",
                )
            } else if let Some(fields) = udp.captures(packet) {
                (
                    vec!["UDP".into()],
                    None,
                    None,
                    None,
                    fields.get(1).unwrap().as_str().parse().unwrap(),
                    "udp",
                )
            } else {
                warnings.push(format!(
                    "line {line_number}: skipped unsupported packet syntax `{packet}`"
                ));
                continue;
            };
        packets.push(ImportedPacket {
            outbound: direction == ">",
            delay_ms,
            flags,
            sequence,
            acknowledgement,
            window,
            payload_len,
            transport,
            line: line_number,
        });
    }
    if packets.is_empty() {
        return Err("packetdrill script contains no supported TCP or UDP packet events".into());
    }
    let mut dsl = format!(
        "tcpform {{ dsl_version = 2 }}\n\n# Imported from packetdrill. System calls and unsupported packet options are listed as warnings.\nprotocol \"{protocol}\" {{\n  clock = \"virtual\"\n"
    );
    let mut previous = None::<String>;
    for (index, packet) in packets.iter().enumerate() {
        let source_role = if packet.outbound {
            local_role
        } else {
            peer_role
        };
        let destination_role = if packet.outbound {
            peer_role
        } else {
            local_role
        };
        let send = format!("packet_{:04}_send", index + 1);
        let recv = format!("packet_{:04}_recv", index + 1);
        dsl.push_str(&format!(
            "\n  # packetdrill line {} · {}\n  step \"{send}\" {{\n    role = \"{source_role}\"\n    action = \"send\"\n    to = \"{destination_role}\"\n",
            packet.line, packet.transport
        ));
        if let Some(previous) = &previous {
            dsl.push_str(&format!("    depends_on = [\"{previous}\"]\n"));
        }
        dsl.push_str("    segment {\n");
        dsl.push_str(&format!(
            "      flags = [{}]\n",
            quoted_flags(&packet.flags)
        ));
        if let Some(sequence) = packet.sequence {
            dsl.push_str(&format!("      seq = {sequence}\n"));
        }
        if let Some(acknowledgement) = packet.acknowledgement {
            dsl.push_str(&format!("      ack = {acknowledgement}\n"));
        }
        if let Some(window) = packet.window {
            dsl.push_str(&format!("      window = {window}\n"));
        }
        if packet.payload_len > 0 {
            dsl.push_str(&format!("      payload_len = {}\n", packet.payload_len));
        }
        if packet.delay_ms > 0 {
            dsl.push_str(&format!("      delay = \"{}ms\"\n", packet.delay_ms));
        }
        dsl.push_str(&format!(
            "    }}\n  }}\n  step \"{recv}\" {{\n    role = \"{destination_role}\"\n    action = \"recv\"\n    depends_on = [\"{send}\"]\n    expect {{ from = \"{source_role}\" flags = [{}] }}\n  }}\n",
            quoted_flags(&packet.flags)
        ));
        previous = Some(recv);
    }
    dsl.push_str(&format!(
        "}}\n\ncases \"{protocol}\" {{\n  case \"packetdrill_import_smoke\" {{ expect = \"pass\" tags = [\"smoke\", \"packetdrill\"] }}\n}}\n"
    ));
    Ok(PacketdrillImport { dsl, warnings })
}

#[derive(Debug)]
struct ImportedPacket {
    outbound: bool,
    delay_ms: u64,
    flags: Vec<String>,
    sequence: Option<usize>,
    acknowledgement: Option<usize>,
    window: Option<usize>,
    payload_len: usize,
    transport: &'static str,
    line: usize,
}

fn payload_length(segment: &Segment) -> Result<usize, String> {
    if let Some(hex) = &segment.hex {
        Ok(crate::parse_hex(hex)?.len())
    } else if let Some(payload) = &segment.payload {
        Ok(payload.len())
    } else {
        usize::try_from(segment.payload_len.unwrap_or(0).max(0))
            .map_err(|_| "payload length is too large".into())
    }
}

fn is_udp(segment: &Segment) -> bool {
    segment
        .flags
        .iter()
        .any(|flag| flag.eq_ignore_ascii_case("udp"))
}

fn packetdrill_flags(flags: &[String]) -> String {
    let mut output = String::new();
    for (name, symbol) in [("SYN", 'S'), ("FIN", 'F'), ("RST", 'R'), ("PSH", 'P')] {
        if flags.iter().any(|flag| flag.eq_ignore_ascii_case(name)) {
            output.push(symbol);
        }
    }
    if flags.iter().any(|flag| flag.eq_ignore_ascii_case("ACK")) {
        output.push('.');
    }
    if output.is_empty() {
        "-".into()
    } else {
        output
    }
}

fn tcpform_flags(flags: &str) -> Vec<String> {
    let mut output = Vec::new();
    for (symbol, name) in [
        ('S', "SYN"),
        ('F', "FIN"),
        ('R', "RST"),
        ('P', "PSH"),
        ('.', "ACK"),
    ] {
        if flags.contains(symbol) {
            output.push(name.into());
        }
    }
    output
}

fn quoted_flags(flags: &[String]) -> String {
    flags
        .iter()
        .map(|flag| format!("\"{flag}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn parse_seconds(value: &str, line: usize) -> Result<f64, String> {
    let value: f64 = value
        .parse()
        .map_err(|_| format!("line {line}: invalid event time"))?;
    if value.is_finite() && value >= 0.0 {
        Ok(value)
    } else {
        Err(format!(
            "line {line}: event time must be finite and non-negative"
        ))
    }
}

fn validate_identifier(value: &str, kind: &str) -> Result<(), String> {
    if value.is_empty()
        || !value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '_' | '-'))
    {
        Err(format!(
            "{kind} may contain only ASCII letters, numbers, `_`, and `-`"
        ))
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn imports_packet_events_and_exports_them_again() {
        let source = r#"
0 socket(..., SOCK_STREAM, IPPROTO_TCP) = 3
+0 < S 0:0(0) win 65535
+0 > S. 0:0(0) ack 1
+.010 < P. 1:5(4) ack 1
+0 > . 1:1(0) ack 5
"#;
        let imported = import(source, "conversation", "server", "client").unwrap();
        assert_eq!(imported.warnings.len(), 1);
        assert!(imported.dsl.contains("delay = \"10ms\""));
        assert!(imported.dsl.contains("payload_len = 4"));
        let blocks = crate::parse_file(&imported.dsl).unwrap();
        let protocol = crate::model::interpret(&blocks).unwrap().remove(0);
        let cases = crate::model::interpret_cases(&blocks).unwrap();
        assert!(crate::Engine::new(protocol.clone())
            .unwrap()
            .run_cases(&cases[0].cases)
            .iter()
            .all(|result| result.passed));
        let exported = export(&protocol, "server").unwrap();
        assert!(exported.contains("< P. 1:5(4) ack 1"));
        assert!(exported.contains("> S. 0:0(0) ack 1"));
    }

    #[test]
    fn rejects_scripts_without_supported_packets() {
        assert!(import("0 socket(...) = 3", "empty", "client", "server").is_err());
    }
}
