//! Conservative TTCN-3 exchange and fixed-layout ASN.1 import.

use crate::{Action, Protocol};
use regex_lite::Regex;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone)]
pub struct StandardsImport {
    pub dsl: String,
    pub warnings: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct TtcnStep {
    name: String,
    role: String,
    action: String,
    #[serde(default)]
    depends_on: Vec<String>,
    #[serde(default)]
    to: Option<String>,
    #[serde(default)]
    payload: Option<String>,
    #[serde(default)]
    hex: Option<String>,
    #[serde(default)]
    flags: Vec<String>,
    #[serde(default)]
    seq: Option<i64>,
    #[serde(default)]
    ack: Option<i64>,
    #[serde(default)]
    from: Option<String>,
}

pub fn export_ttcn3(protocol: &Protocol) -> Result<String, String> {
    let module = ttcn_identifier(&protocol.name);
    let mut output = format!(
        "// Generated by tcpform. tcpform-step annotations preserve lossless re-import.\nmodule {module} {{\n  type component TcpformComponent {{ port TcpformPort p; }}\n  type port TcpformPort message {{ inout charstring; }}\n\n  testcase tc_{}() runs on TcpformComponent {{\n",
        ttcn_identifier(&protocol.name).to_ascii_lowercase()
    );
    for step in &protocol.steps {
        if !matches!(
            step.action,
            Action::Send
                | Action::SendRaw
                | Action::Recv
                | Action::RecvRaw
                | Action::Ack
                | Action::Nack
                | Action::Wait
                | Action::Open
                | Action::Close
                | Action::Reset
                | Action::Drop
                | Action::Log
        ) {
            return Err(format!(
                "TTCN-3 export does not losslessly support action `{}` in step `{}`",
                step.action.as_str(),
                step.name
            ));
        }
        let payload = step
            .segment
            .as_ref()
            .and_then(|segment| segment.payload.clone())
            .or_else(|| {
                step.expect
                    .as_ref()
                    .and_then(|expect| expect.payload.clone())
            });
        let hex = step
            .segment
            .as_ref()
            .and_then(|segment| segment.hex.clone())
            .or_else(|| {
                step.expect
                    .as_ref()
                    .and_then(|expect| expect.hex.as_ref().map(|bytes| crate::bytes_to_hex(bytes)))
            });
        let segment = step.segment.as_ref();
        let expect = step.expect.as_ref();
        let annotation = TtcnStep {
            name: step.name.clone(),
            role: step.role.clone(),
            action: step.action.as_str().to_string(),
            depends_on: step.depends_on.clone(),
            to: step.to.clone(),
            payload: payload.clone(),
            hex: hex.clone(),
            flags: segment
                .map(|value| value.flags.clone())
                .or_else(|| expect.map(|value| value.flags.clone()))
                .unwrap_or_default(),
            seq: segment.and_then(|value| value.seq),
            ack: segment.and_then(|value| value.ack),
            from: expect.and_then(|value| value.from.clone()),
        };
        output.push_str(&format!(
            "    // tcpform-step: {}\n",
            serde_json::to_string(&annotation).map_err(|error| error.to_string())?
        ));
        let value = payload
            .or(hex.map(|value| format!("hex:{value}")))
            .unwrap_or_else(|| step.action.as_str().to_string());
        if matches!(step.action, Action::Recv | Action::RecvRaw) {
            output.push_str(&format!(
                "    p.receive(\"{}\"); // role={} step={}\n",
                ttcn_escape(&value),
                step.role,
                step.name
            ));
        } else if matches!(
            step.action,
            Action::Send | Action::SendRaw | Action::Ack | Action::Nack
        ) {
            output.push_str(&format!(
                "    p.send(\"{}\"); // role={} step={}\n",
                ttcn_escape(&value),
                step.role,
                step.name
            ));
        } else {
            output.push_str(&format!(
                "    log(\"tcpform {}: {}\"); // role={} step={}\n",
                step.action.as_str(),
                ttcn_escape(&value),
                step.role,
                step.name
            ));
        }
    }
    output.push_str(&format!(
        "  }}\n\n  control {{ execute(tc_{}()); }}\n}}\n",
        ttcn_identifier(&protocol.name).to_ascii_lowercase()
    ));
    Ok(output)
}

pub fn import_ttcn3(source: &str, protocol: &str) -> Result<StandardsImport, String> {
    let mut steps = Vec::new();
    for (line, text) in source.lines().enumerate() {
        if let Some(annotation) = text.trim().strip_prefix("// tcpform-step:") {
            let step: TtcnStep = serde_json::from_str(annotation.trim()).map_err(|error| {
                format!(
                    "invalid tcpform-step annotation on line {}: {error}",
                    line + 1
                )
            })?;
            steps.push(step);
        }
    }
    if steps.is_empty() {
        return Err("TTCN-3 import requires tcpform-step annotations; unannotated TTCN-3 semantics are not guessed".into());
    }
    let mut dsl = format!(
        "tcpform {{ dsl_version = 2 }}\n\n# Imported from annotated TTCN-3.\nprotocol \"{}\" {{\n",
        dsl_escape(protocol)
    );
    for step in steps {
        let action = parse_action(&step.action)?;
        dsl.push_str(&format!(
            "  step \"{}\" {{\n    role = \"{}\"\n    action = \"{}\"\n",
            dsl_escape(&step.name),
            dsl_escape(&step.role),
            action
        ));
        if !step.depends_on.is_empty() {
            dsl.push_str(&format!(
                "    depends_on = [{}]\n",
                step.depends_on
                    .iter()
                    .map(|value| format!("\"{}\"", dsl_escape(value)))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if let Some(to) = step.to {
            dsl.push_str(&format!("    to = \"{}\"\n", dsl_escape(&to)));
        }
        if matches!(action, "send" | "send_raw" | "ack" | "nack") {
            dsl.push_str("    segment {");
            if !step.flags.is_empty() {
                dsl.push_str(&format!(
                    " flags = [{}]",
                    step.flags
                        .iter()
                        .map(|value| format!("\"{}\"", dsl_escape(value)))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            if let Some(seq) = step.seq {
                dsl.push_str(&format!(" seq = {seq}"));
            }
            if let Some(ack) = step.ack {
                dsl.push_str(&format!(" ack = {ack}"));
            }
            if let Some(payload) = step.payload {
                dsl.push_str(&format!(" payload = \"{}\"", dsl_escape(&payload)));
            }
            if let Some(hex) = step.hex {
                dsl.push_str(&format!(" hex = \"{}\"", dsl_escape(&hex)));
            }
            dsl.push_str(" }\n");
        } else if matches!(action, "recv" | "recv_raw" | "drop") {
            dsl.push_str("    expect {");
            if !step.flags.is_empty() {
                dsl.push_str(&format!(
                    " flags = [{}]",
                    step.flags
                        .iter()
                        .map(|value| format!("\"{}\"", dsl_escape(value)))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            if let Some(from) = step.from {
                dsl.push_str(&format!(" from = \"{}\"", dsl_escape(&from)));
            }
            if let Some(payload) = step.payload {
                dsl.push_str(&format!(" payload = \"{}\"", dsl_escape(&payload)));
            }
            if let Some(hex) = step.hex {
                dsl.push_str(&format!(" hex = \"{}\"", dsl_escape(&hex)));
            }
            dsl.push_str(" }\n");
        }
        dsl.push_str("  }\n");
    }
    dsl.push_str("}\n");
    Ok(StandardsImport {
        dsl,
        warnings: Vec::new(),
    })
}

pub fn import_asn1(
    source: &str,
    type_name: Option<&str>,
    protocol: &str,
) -> Result<StandardsImport, String> {
    let cleaned = source
        .lines()
        .map(|line| line.split("--").next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n");
    let mut selected = None;
    for (name, body) in sequence_definitions(&cleaned)? {
        if type_name.is_none_or(|wanted| wanted == name) {
            selected = Some((name, body));
            break;
        }
    }
    let (name, body) = selected.ok_or_else(|| match type_name {
        Some(name) => format!("ASN.1 SEQUENCE `{name}` not found"),
        None => "ASN.1 input contains no SEQUENCE definition".into(),
    })?;
    let fields = split_fields(body)?;
    let mut offset = 0usize;
    let mut rendered = Vec::new();
    for (field, kind) in fields {
        if kind.contains("OPTIONAL") || kind.contains("DEFAULT") {
            return Err(format!(
                "ASN.1 field `{field}` is optional/dynamic; fixed layout cannot be inferred safely"
            ));
        }
        let (length, format) = asn1_shape(&field, &kind)?;
        rendered.push((asn_identifier(&field), offset, length, format));
        offset = offset
            .checked_add(length)
            .ok_or("ASN.1 layout is too large")?;
    }
    let mut dsl = format!("tcpform {{ dsl_version = 2 }}\n\n# Fixed-layout projection of ASN.1 {name}; this is not BER/DER encoding.\nprotocol \"{}\" {{\n  description = \"Imported fixed-layout ASN.1 SEQUENCE {}\"\n  header_schema \"{}\" {{\n    offset = 0\n    endian = \"big\"\n    fields = {{\n", dsl_escape(protocol), dsl_escape(name), asn_identifier(name));
    for (field, field_offset, length, format) in rendered {
        dsl.push_str(&format!("      {field} = {{ offset = {field_offset} length = {length} format = \"{format}\" }}\n"));
    }
    dsl.push_str(&format!("    }}\n  }}\n  step \"send_{}\" {{ role=\"client\" action=\"send\" to=\"server\" segment {{ hex=\"{}\" }} }}\n  step \"recv_{}\" {{ role=\"server\" action=\"recv\" depends_on=[\"send_{}\"] expect {{ from=\"client\" }} }}\n}}\n", asn_identifier(name), "00".repeat(offset), asn_identifier(name), asn_identifier(name)));
    Ok(StandardsImport { dsl, warnings: vec!["Generated layout is an explicit fixed-width projection, not BER, DER, CER, or PER. Review encoding rules before interoperability use.".into()] })
}

fn sequence_definitions(source: &str) -> Result<Vec<(&str, &str)>, String> {
    let header = Regex::new(r"([A-Za-z][A-Za-z0-9-]*)\s*::=\s*SEQUENCE\s*\{").unwrap();
    let mut definitions = Vec::new();
    for captures in header.captures_iter(source) {
        let name = captures.get(1).unwrap().as_str();
        let start = captures.get(0).unwrap().end();
        let mut depth = 1usize;
        let mut end = None;
        for (offset, character) in source[start..].char_indices() {
            match character {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = Some(start + offset);
                        break;
                    }
                }
                _ => {}
            }
        }
        let end = end.ok_or_else(|| format!("ASN.1 SEQUENCE `{name}` has no closing brace"))?;
        definitions.push((name, &source[start..end]));
    }
    Ok(definitions)
}

fn split_fields(body: &str) -> Result<Vec<(String, String)>, String> {
    let mut fields = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (index, character) in body.char_indices() {
        match character {
            '(' | '{' => depth += 1,
            ')' | '}' => depth -= 1,
            ',' if depth == 0 => {
                fields.push(&body[start..index]);
                start = index + 1;
            }
            _ => {}
        }
        if depth < 0 {
            return Err("unbalanced ASN.1 field constraint".into());
        }
    }
    fields.push(&body[start..]);
    fields
        .into_iter()
        .filter(|field| !field.trim().is_empty())
        .map(|field| {
            let mut parts = field.split_whitespace();
            let name = parts.next().ok_or("empty ASN.1 field")?.to_string();
            let kind = parts.collect::<Vec<_>>().join(" ");
            if kind.is_empty() {
                Err(format!("ASN.1 field `{name}` has no type"))
            } else {
                Ok((name, kind))
            }
        })
        .collect()
}

fn asn1_shape(field: &str, kind: &str) -> Result<(usize, &'static str), String> {
    let upper = kind.to_ascii_uppercase();
    if upper.starts_with("BOOLEAN") {
        return Ok((1, "uint"));
    }
    if upper.starts_with("ENUMERATED") {
        let body = kind
            .split_once('{')
            .and_then(|(_, rest)| rest.rsplit_once('}').map(|(body, _)| body))
            .ok_or_else(|| {
                format!("ASN.1 ENUMERATED `{field}` requires explicit numeric members")
            })?;
        let member = Regex::new(r"[A-Za-z][A-Za-z0-9-]*\s*\(\s*([0-9]+)\s*\)").unwrap();
        let values: Vec<u128> = member
            .captures_iter(body)
            .filter_map(|capture| capture.get(1)?.as_str().parse().ok())
            .collect();
        if values.is_empty()
            || values.len()
                != body
                    .split(',')
                    .filter(|value| !value.trim().is_empty())
                    .count()
        {
            return Err(format!("ASN.1 ENUMERATED `{field}` requires an explicit non-negative value for every member"));
        }
        return Ok((unsigned_width(*values.iter().max().unwrap())?, "uint"));
    }
    let size = Regex::new(r"(?i)SIZE\s*\(\s*([0-9]+)\s*\)").unwrap();
    if upper.starts_with("OCTET STRING") || upper.starts_with("IA5STRING") {
        let length = size
            .captures(kind)
            .and_then(|capture| capture.get(1))
            .and_then(|value| value.as_str().parse::<usize>().ok())
            .ok_or_else(|| format!("ASN.1 field `{field}` requires an exact SIZE(n) constraint"))?;
        if length == 0 {
            return Err(format!("ASN.1 field `{field}` has zero size"));
        }
        return Ok((
            length,
            if upper.starts_with("OCTET STRING") {
                "hex"
            } else {
                "ascii"
            },
        ));
    }
    if upper.starts_with("INTEGER") {
        let range = Regex::new(r"\(\s*0\s*\.\.\s*([0-9]+)\s*\)").unwrap();
        let maximum = range
            .captures(kind)
            .and_then(|capture| capture.get(1))
            .and_then(|value| value.as_str().parse::<u128>().ok())
            .ok_or_else(|| {
                format!("ASN.1 INTEGER `{field}` requires a non-negative (0..max) constraint")
            })?;
        let length = unsigned_width(maximum)
            .map_err(|_| format!("ASN.1 INTEGER `{field}` exceeds 64 bits"))?;
        return Ok((length, "uint"));
    }
    Err(format!(
        "ASN.1 field `{field}` uses unsupported or variable type `{kind}`"
    ))
}

fn unsigned_width(maximum: u128) -> Result<usize, String> {
    if maximum <= u8::MAX.into() {
        Ok(1)
    } else if maximum <= u16::MAX.into() {
        Ok(2)
    } else if maximum <= u32::MAX.into() {
        Ok(4)
    } else if maximum <= u64::MAX.into() {
        Ok(8)
    } else {
        Err("value exceeds 64 bits".into())
    }
}

fn parse_action(action: &str) -> Result<&str, String> {
    const ACTIONS: &[&str] = &[
        "send", "send_raw", "recv", "recv_raw", "ack", "nack", "wait", "open", "close", "reset",
        "drop", "log",
    ];
    ACTIONS
        .iter()
        .copied()
        .find(|value| *value == action)
        .ok_or_else(|| format!("unsupported annotated TTCN-3 action `{action}`"))
}
fn ttcn_identifier(value: &str) -> String {
    let mut out: String = value
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert_str(0, "Tcpform_");
    }
    out
}
fn asn_identifier(value: &str) -> String {
    ttcn_identifier(value).to_ascii_lowercase()
}
fn ttcn_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace(['\n', '\r'], " ")
}
fn dsl_escape(value: &str) -> String {
    ttcn_escape(value)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{model::interpret, parse_file};
    #[test]
    fn imports_fixed_asn1_and_rejects_dynamic_fields() {
        let source = "Demo DEFINITIONS ::= BEGIN\nMessage ::= SEQUENCE { version INTEGER (0..255), enabled BOOLEAN, mode ENUMERATED { on(1), off(2) }, payload OCTET STRING (SIZE(4)) }\nEND";
        let imported = import_asn1(source, Some("Message"), "demo").unwrap();
        assert!(imported
            .dsl
            .contains("payload = { offset = 3 length = 4 format = \"hex\" }"));
        interpret(&parse_file(&imported.dsl).unwrap()).unwrap();
        assert!(
            import_asn1("M ::= SEQUENCE { data OCTET STRING }", None, "x")
                .unwrap_err()
                .contains("SIZE")
        );
    }

    #[test]
    fn annotated_ttcn3_round_trips_protocol_steps() {
        let protocol = interpret(&parse_file(r#"protocol "demo" {
          step "request" { role="client" action="send" to="server" segment { payload="hello" } }
          step "response" { role="server" action="recv" depends_on=["request"] expect { payload="world" } }
        }"#).unwrap()).unwrap().remove(0);
        let ttcn = export_ttcn3(&protocol).unwrap();
        assert!(ttcn.contains("p.send(\"hello\")"));
        let imported = import_ttcn3(&ttcn, "roundtrip").unwrap();
        let roundtrip = interpret(&parse_file(&imported.dsl).unwrap())
            .unwrap()
            .remove(0);
        assert_eq!(roundtrip.steps.len(), 2);
        assert_eq!(
            roundtrip.steps[0]
                .segment
                .as_ref()
                .unwrap()
                .payload
                .as_deref(),
            Some("hello")
        );
        assert_eq!(roundtrip.steps[1].depends_on, ["request"]);
    }
}
